import type { ThemeDefinition, ThemeVariant } from "./types";
import { THEME_FORMAT } from "./types";

type BuiltinSemanticPalette = Required<
  NonNullable<ThemeVariant["appearance"]["palette"]>
>;

function variant(
  background: string,
  surface: string,
  text: string,
  mutedText: string,
  border: string,
  accent: string,
  overlay: string,
  overlayOpacity: number,
  surfaceOpacity: number,
  chrome: Pick<
    ThemeVariant["appearance"],
    "layout" | "iconStyle" | "decorations"
  > = {
    layout: "native",
    iconStyle: "native",
    decorations: "none",
  },
): ThemeVariant {
  return {
    background: {
      color: background,
      position: { x: 50, y: 50 },
      brightness: 1,
      blur: 0,
      overlay,
      overlayOpacity,
    },
    appearance: {
      accent,
      surface,
      surfaceOpacity,
      text,
      mutedText,
      border,
      radius: 14,
      focusOpacity: 0.84,
      focusBlur: 12,
      ...chrome,
    },
    motion: {
      intensity: 0.5,
      parallax: 8,
      targetFps: 30,
    },
  };
}

function detailedVariant(
  base: ThemeVariant,
  palette: BuiltinSemanticPalette,
  motion: Partial<ThemeVariant["motion"]>,
  radius = base.appearance.radius,
): ThemeVariant {
  return {
    ...base,
    appearance: { ...base.appearance, palette, radius },
    motion: { ...base.motion, ...motion },
  };
}

export const nativeRefined: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.native-refined",
  version: "1.0.0",
  metadata: {
    name: "Native Refined",
    description:
      "A quieter, more deliberate interpretation of the native workspace.",
    author: "Codex Styler contributors",
    license: "CC-BY-4.0",
    tags: ["minimal", "native", "light", "dark"],
    preview: "previews/native-refined.webp",
    recommendedCompanionId: "moss-gecko",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: detailedVariant(
      variant(
        "#f1f3f6",
        "#fbfcfd",
        "#1b2027",
        "#59626f",
        "#c9d0d9",
        "#4e739d",
        "#e9edf2",
        0.04,
        0.92,
        { layout: "native", iconStyle: "contained", decorations: "subtle" },
      ),
      {
        canvas: "#f1f3f6",
        surfaceRaised: "#ffffff",
        surfaceOverlay: "#f6f7f9",
        surfaceSunken: "#e8ebef",
        control: "#eef1f4",
        controlHover: "#e5e9ee",
        controlActive: "#dbe4ef",
        textTertiary: "#707a87",
        onAccent: "#f8fbff",
        borderSubtle: "#dce1e7",
        borderStrong: "#7e8997",
        focus: "#4e739d",
        success: "#2f6f52",
        warning: "#805a16",
        danger: "#a64146",
        info: "#356b9a",
        added: "#2f6f52",
        modified: "#805a16",
        deleted: "#a64146",
      },
      { intensity: 0.5, parallax: 3, targetFps: 30 },
      12,
    ),
    dark: detailedVariant(
      variant(
        "#111419",
        "#1b1f25",
        "#f2f4f7",
        "#b1b8c2",
        "#343b46",
        "#8eb5df",
        "#0b0e12",
        0.12,
        0.93,
        { layout: "native", iconStyle: "contained", decorations: "subtle" },
      ),
      {
        canvas: "#111419",
        surfaceRaised: "#252a32",
        surfaceOverlay: "#2b313a",
        surfaceSunken: "#11151a",
        control: "#242a32",
        controlHover: "#2e3540",
        controlActive: "#34445a",
        textTertiary: "#8b94a0",
        onAccent: "#101a25",
        borderSubtle: "#2a3039",
        borderStrong: "#687382",
        focus: "#8eb5df",
        success: "#75c99d",
        warning: "#e2b664",
        danger: "#e27f7e",
        info: "#84b7e3",
        added: "#75c99d",
        modified: "#e2b664",
        deleted: "#e27f7e",
      },
      { intensity: 0.5, parallax: 3, targetFps: 30 },
      12,
    ),
  },
  scene: {
    layers: [
      {
        id: "soft-vignette",
        type: "vignette",
        opacity: 0.14,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "native-preview",
      path: "previews/native-refined.webp",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Native Refined",
      description:
        "The native workspace, with calmer contrast and cleaner rhythm.",
    },
    "zh-CN": {
      name: "原生精修",
      description: "保留原生秩序，降低干扰并重新校准明暗节奏。",
    },
  },
};

export const nocturneStudio: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.nocturne-studio",
  version: "1.0.0",
  metadata: {
    name: "Nocturne Studio",
    description:
      "A cinematic midnight workspace shaped by ink, glass, and amber light.",
    author: "Codex Styler contributors",
    license: "CC-BY-4.0",
    tags: ["cinematic", "dark", "image", "studio"],
    preview: "previews/nocturne-studio.webp",
    recommendedCompanionId: "moss-gecko",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: detailedVariant(
      variant(
        "#d6d3cc",
        "#f0ede6",
        "#24231f",
        "#514d44",
        "#b8b3a8",
        "#a35d37",
        "#ddd6ca",
        0.16,
        0.82,
        {
          layout: "editorial",
          iconStyle: "themed",
          decorations: "expressive",
        },
      ),
      {
        canvas: "#d6d3cc",
        surfaceRaised: "#faf7f0",
        surfaceOverlay: "#ece6dc",
        surfaceSunken: "#d8d3ca",
        control: "#e8e1d6",
        controlHover: "#dccfc1",
        controlActive: "#cfbea9",
        textTertiary: "#6d6359",
        onAccent: "#fff8ef",
        borderSubtle: "#c8c0b5",
        borderStrong: "#86796c",
        focus: "#9b5431",
        success: "#2d6f50",
        warning: "#86550e",
        danger: "#a43e38",
        info: "#2f6389",
        added: "#2d6f50",
        modified: "#86550e",
        deleted: "#a43e38",
      },
      { intensity: 0.42, parallax: 6, targetFps: 30 },
      12,
    ),
    dark: {
      ...detailedVariant(
        variant(
          "#090b0d",
          "#14181a",
          "#f5efe6",
          "#b8b2aa",
          "#34383a",
          "#e9a066",
          "#071014",
          0.42,
          0.72,
          {
            layout: "editorial",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#090b0d",
          surfaceRaised: "#1c2225",
          surfaceOverlay: "#222a2d",
          surfaceSunken: "#0e1214",
          control: "#20272a",
          controlHover: "#2a3336",
          controlActive: "#343f42",
          textTertiary: "#999c99",
          onAccent: "#241207",
          borderSubtle: "#2b3235",
          borderStrong: "#596166",
          focus: "#e9a066",
          success: "#70bd8d",
          warning: "#e1ae5b",
          danger: "#e47a72",
          info: "#7fb7de",
          added: "#70bd8d",
          modified: "#e1ae5b",
          deleted: "#e47a72",
        },
        { intensity: 0.48, parallax: 8, targetFps: 30 },
        12,
      ),
      background: {
        color: "#090b0d",
        image: "assets/nocturne-studio.webp",
        position: { x: 58, y: 46 },
        brightness: 0.78,
        blur: 0,
        overlay: "#071014",
        overlayOpacity: 0.42,
      },
    },
  },
  scene: {
    layers: [
      {
        id: "studio-background",
        type: "image",
        asset: "assets/nocturne-studio.webp",
        opacity: 1,
        blendMode: "normal",
        parallax: 5,
      },
      {
        id: "studio-vignette",
        type: "vignette",
        opacity: 0.55,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "nocturne-background",
      path: "assets/nocturne-studio.webp",
      type: "background",
      license: "CC-BY-4.0",
    },
    {
      id: "nocturne-preview",
      path: "previews/nocturne-studio.webp",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Nocturne Studio",
      description:
        "Ink-dark surfaces, quiet glass, and a controlled amber horizon.",
    },
    "zh-CN": {
      name: "夜曲工作室",
      description: "墨色表面、克制玻璃与一线温暖的琥珀光。",
    },
  },
};

export const quietGarden: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.quiet-garden",
  version: "1.0.0",
  metadata: {
    name: "Quiet Garden",
    description:
      "A living garden workspace with calm, legible translucent surfaces.",
    author: "Codex Styler contributors",
    license: "CC-BY-4.0",
    tags: ["nature", "calm", "image", "light", "dark"],
    preview: "previews/quiet-garden.webp",
    recommendedCompanionId: "moss-gecko",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: {
      ...detailedVariant(
        variant(
          "#d9dfd2",
          "#f2f1e8",
          "#263128",
          "#4f5d51",
          "#b9c2b5",
          "#56745b",
          "#dbe3d6",
          0.18,
          0.76,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#d9dfd2",
          surfaceRaised: "#faf9f0",
          surfaceOverlay: "#e7ebe0",
          surfaceSunken: "#dce3d7",
          control: "#e5e9df",
          controlHover: "#d8dfd4",
          controlActive: "#cbd7ca",
          textTertiary: "#687269",
          onAccent: "#fbfff8",
          borderSubtle: "#c8d0c5",
          borderStrong: "#7f8d80",
          focus: "#56745b",
          success: "#2f7047",
          warning: "#7b5a0c",
          danger: "#a4443d",
          info: "#376686",
          added: "#2f7047",
          modified: "#7b5a0c",
          deleted: "#a4443d",
        },
        { intensity: 0.34, parallax: 7, targetFps: 30 },
        18,
      ),
      background: {
        color: "#d9dfd2",
        image: "assets/quiet-garden.webp",
        position: { x: 52, y: 50 },
        brightness: 1,
        blur: 0,
        overlay: "#dce5d9",
        overlayOpacity: 0.14,
      },
    },
    dark: {
      ...detailedVariant(
        variant(
          "#101612",
          "#18211b",
          "#edf2e8",
          "#b4bdb5",
          "#364339",
          "#9fc29a",
          "#0d1510",
          0.34,
          0.68,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#101612",
          surfaceRaised: "#202b23",
          surfaceOverlay: "#263229",
          surfaceSunken: "#111914",
          control: "#243028",
          controlHover: "#2e3d33",
          controlActive: "#394a3e",
          textTertiary: "#8f9b91",
          onAccent: "#102015",
          borderSubtle: "#2c392f",
          borderStrong: "#59695d",
          focus: "#9fc29a",
          success: "#74c58b",
          warning: "#dfb45c",
          danger: "#df7d76",
          info: "#83b8d9",
          added: "#74c58b",
          modified: "#dfb45c",
          deleted: "#df7d76",
        },
        { intensity: 0.38, parallax: 8, targetFps: 30 },
        18,
      ),
      background: {
        color: "#101612",
        image: "assets/quiet-garden.webp",
        position: { x: 52, y: 50 },
        brightness: 0.64,
        blur: 0,
        overlay: "#07110b",
        overlayOpacity: 0.38,
      },
    },
  },
  scene: {
    layers: [
      {
        id: "garden-background",
        type: "image",
        asset: "assets/quiet-garden.webp",
        opacity: 1,
        blendMode: "normal",
        parallax: 8,
      },
      {
        id: "garden-vignette",
        type: "vignette",
        opacity: 0.34,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "garden-background",
      path: "assets/quiet-garden.webp",
      type: "background",
      license: "CC-BY-4.0",
    },
    {
      id: "garden-preview",
      path: "previews/quiet-garden.webp",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Quiet Garden",
      description:
        "A quiet garden scene with readable, translucent workspace surfaces.",
    },
    "zh-CN": {
      name: "静谧花园",
      description: "安静的花园场景，搭配清晰易读的半透明工作区表面。",
    },
  },
};

export const gildedGrandeur: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.gilded-grandeur",
  version: "1.0.0",
  metadata: {
    name: "Gilded Grandeur",
    description:
      "An obsidian-and-gold workspace with architectural depth and precise luminous accents.",
    author: "Codex Styler contributors",
    license: "CC-BY-4.0",
    tags: ["gold", "luxury", "image", "editorial", "light", "dark"],
    preview: "previews/gilded-grandeur.webp",
    recommendedCompanionId: "reset-god",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: {
      ...detailedVariant(
        variant(
          "#d6bd80",
          "#f7edcf",
          "#2d210f",
          "#6e5b3a",
          "#aa8c4e",
          "#87560b",
          "#f1e2bb",
          0.38,
          0.88,
          {
            layout: "editorial",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#dfc98f",
          surfaceRaised: "#fff6dc",
          surfaceOverlay: "#f5e5bc",
          surfaceSunken: "#e8d39e",
          control: "#f0dfb5",
          controlHover: "#e7cf93",
          controlActive: "#dbc17c",
          textTertiary: "#77613d",
          onAccent: "#fff9e8",
          borderSubtle: "#cdb271",
          borderStrong: "#8f6d28",
          focus: "#87560b",
          success: "#236b43",
          warning: "#81500d",
          danger: "#a7352e",
          info: "#245d8a",
          added: "#236b43",
          modified: "#81500d",
          deleted: "#a7352e",
        },
        { intensity: 0.42, parallax: 6, targetFps: 30 },
        10,
      ),
      background: {
        color: "#d6bd80",
        image: "assets/gilded-grandeur.webp",
        position: { x: 54, y: 48 },
        brightness: 1.04,
        blur: 0,
        overlay: "#f0dfb5",
        overlayOpacity: 0.38,
      },
    },
    dark: {
      ...detailedVariant(
        variant(
          "#090704",
          "#18130b",
          "#fff2cd",
          "#c0a875",
          "#5b4721",
          "#e8bd55",
          "#080602",
          0.34,
          0.76,
          {
            layout: "editorial",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#0b0804",
          surfaceRaised: "#21190c",
          surfaceOverlay: "#2a1e0d",
          surfaceSunken: "#100c06",
          control: "#2b210f",
          controlHover: "#3a2b12",
          controlActive: "#4b3714",
          textTertiary: "#a98c59",
          onAccent: "#211400",
          borderSubtle: "#46381f",
          borderStrong: "#80652d",
          focus: "#f2c75b",
          success: "#72b881",
          warning: "#f0bf4a",
          danger: "#e9786e",
          info: "#85b9e6",
          added: "#72b881",
          modified: "#f0bf4a",
          deleted: "#e9786e",
        },
        { intensity: 0.48, parallax: 7, targetFps: 30 },
        10,
      ),
      background: {
        color: "#090704",
        image: "assets/gilded-grandeur.webp",
        position: { x: 54, y: 48 },
        brightness: 0.82,
        blur: 0,
        overlay: "#080602",
        overlayOpacity: 0.34,
      },
    },
  },
  scene: {
    layers: [
      {
        id: "gilded-background",
        type: "image",
        asset: "assets/gilded-grandeur.webp",
        opacity: 1,
        blendMode: "normal",
        parallax: 7,
      },
      {
        id: "gilded-vignette",
        type: "vignette",
        opacity: 0.4,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "gilded-background",
      path: "assets/gilded-grandeur.webp",
      type: "background",
      license: "CC-BY-4.0",
    },
    {
      id: "gilded-preview",
      path: "previews/gilded-grandeur.webp",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Gilded Grandeur",
      description:
        "Obsidian architecture, warm gold light, and deeply polished workspace surfaces.",
    },
    "zh-CN": {
      name: "金辉盛境",
      description: "黑曜石建筑、鎏金暖光与层次分明的华丽工作区表面。",
    },
  },
};

export const merryBigTop: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.merry-big-top",
  version: "1.0.0",
  metadata: {
    name: "Merry Big Top",
    description:
      "A playful theatrical workspace with tactile circus color and buoyant motion.",
    author: "Codex Styler contributors",
    license: "CC-BY-4.0",
    tags: ["circus", "playful", "image", "colorful", "light", "dark"],
    preview: "previews/merry-big-top.webp",
    recommendedCompanionId: "token-thief",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: {
      ...detailedVariant(
        variant(
          "#d99a61",
          "#fff1d9",
          "#2b1b19",
          "#715a54",
          "#c58a70",
          "#b72f2d",
          "#ffe7c2",
          0.28,
          0.88,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#efbd83",
          surfaceRaised: "#fff8e8",
          surfaceOverlay: "#ffe7c8",
          surfaceSunken: "#f2cba4",
          control: "#f9dcc0",
          controlHover: "#efc7a7",
          controlActive: "#e6b38f",
          textTertiary: "#76574e",
          onAccent: "#fff8e8",
          borderSubtle: "#d7a188",
          borderStrong: "#9f554c",
          focus: "#9f2928",
          success: "#17705d",
          warning: "#85520b",
          danger: "#a72f3b",
          info: "#176785",
          added: "#17705d",
          modified: "#85520b",
          deleted: "#a72f3b",
        },
        { intensity: 0.72, parallax: 11, targetFps: 60 },
        18,
      ),
      background: {
        color: "#d99a61",
        image: "assets/merry-big-top.webp",
        position: { x: 55, y: 48 },
        brightness: 1.04,
        blur: 0,
        overlay: "#ffe3bd",
        overlayOpacity: 0.28,
      },
    },
    dark: {
      ...detailedVariant(
        variant(
          "#100b14",
          "#241923",
          "#fff2dc",
          "#cdb9ac",
          "#5a3d4b",
          "#ff755e",
          "#0b0b13",
          0.34,
          0.74,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "expressive",
          },
        ),
        {
          canvas: "#100b14",
          surfaceRaised: "#30202c",
          surfaceOverlay: "#3a2433",
          surfaceSunken: "#171018",
          control: "#352431",
          controlHover: "#463044",
          controlActive: "#5a354d",
          textTertiary: "#b798a9",
          onAccent: "#2c1010",
          borderSubtle: "#5a3d4b",
          borderStrong: "#9a5a6d",
          focus: "#ff8b73",
          success: "#61c8a3",
          warning: "#f4bd55",
          danger: "#ff7e86",
          info: "#68c7df",
          added: "#61c8a3",
          modified: "#f4bd55",
          deleted: "#ff7e86",
        },
        { intensity: 0.78, parallax: 13, targetFps: 60 },
        18,
      ),
      background: {
        color: "#100b14",
        image: "assets/merry-big-top.webp",
        position: { x: 55, y: 48 },
        brightness: 0.82,
        blur: 0,
        overlay: "#0b0b13",
        overlayOpacity: 0.34,
      },
    },
  },
  scene: {
    layers: [
      {
        id: "big-top-background",
        type: "image",
        asset: "assets/merry-big-top.webp",
        opacity: 1,
        blendMode: "normal",
        parallax: 13,
      },
      {
        id: "big-top-vignette",
        type: "vignette",
        opacity: 0.28,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "big-top-background",
      path: "assets/merry-big-top.webp",
      type: "background",
      license: "CC-BY-4.0",
    },
    {
      id: "big-top-preview",
      path: "previews/merry-big-top.webp",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Merry Big Top",
      description:
        "A tactile circus stage with playful color, rounded chrome, and buoyant motion.",
    },
    "zh-CN": {
      name: "滑稽马戏团",
      description: "有趣的马戏舞台、圆润组件、活泼配色与轻快动态。",
    },
  },
};

export const caishenReadable: ThemeDefinition = {
  format: THEME_FORMAT,
  id: "codex-styler.caishen-readable",
  version: "1.0.0",
  metadata: {
    name: "Caishen Readable",
    description:
      "A bright fortune-desk workspace tuned for readable Codex surfaces.",
    author: "ChannelerH",
    license: "CC-BY-4.0",
    tags: ["fortune", "light", "image", "warm", "readable"],
    homepage:
      "https://codex-theme-gallery.howardhua.chatgpt.site/themes/caishen-readable?utm_source=xuhuanstudio-codex-styler&utm_medium=github-pr&utm_campaign=caishen-readable",
    preview: "previews/caishen-readable.png",
  },
  compatibility: {
    styler: { minimumVersion: "0.1.0" },
    codex: {
      mode: "semantic",
      testedVersions: ["26.707.72221", "26.707.91948"],
    },
  },
  variants: {
    light: {
      ...detailedVariant(
        variant(
          "#f7eadc",
          "#fff9ef",
          "#241d17",
          "#6d5a4b",
          "#ddc8af",
          "#c15a2a",
          "#fff1dc",
          0.2,
          0.86,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "subtle",
          },
        ),
        {
          canvas: "#f7eadc",
          surfaceRaised: "#fffaf1",
          surfaceOverlay: "#f6e4cc",
          surfaceSunken: "#efd5ba",
          control: "#f5dfc6",
          controlHover: "#edcfaf",
          controlActive: "#e2bd99",
          textTertiary: "#826b58",
          onAccent: "#fff8ee",
          borderSubtle: "#e4cbb1",
          borderStrong: "#a97651",
          focus: "#c15a2a",
          success: "#2f7047",
          warning: "#8b5a0d",
          danger: "#a33f34",
          info: "#2d6689",
          added: "#2f7047",
          modified: "#8b5a0d",
          deleted: "#a33f34",
        },
        { intensity: 0.34, parallax: 6, targetFps: 30 },
        16,
      ),
      background: {
        color: "#f7eadc",
        image: "assets/caishen-readable.png",
        position: { x: 74, y: 50 },
        brightness: 1.08,
        blur: 0,
        overlay: "#fff1dc",
        overlayOpacity: 0.2,
      },
    },
    dark: {
      ...detailedVariant(
        variant(
          "#1a120d",
          "#251b15",
          "#fff0dc",
          "#d2bda8",
          "#5f4535",
          "#f0a24f",
          "#120c08",
          0.48,
          0.76,
          {
            layout: "immersive",
            iconStyle: "themed",
            decorations: "subtle",
          },
        ),
        {
          canvas: "#1a120d",
          surfaceRaised: "#302219",
          surfaceOverlay: "#39291e",
          surfaceSunken: "#160f0b",
          control: "#34261d",
          controlHover: "#443126",
          controlActive: "#553d2d",
          textTertiary: "#b99b82",
          onAccent: "#2b1608",
          borderSubtle: "#4c382b",
          borderStrong: "#93684b",
          focus: "#f0a24f",
          success: "#78c991",
          warning: "#e4b661",
          danger: "#e77c73",
          info: "#83b9df",
          added: "#78c991",
          modified: "#e4b661",
          deleted: "#e77c73",
        },
        { intensity: 0.38, parallax: 7, targetFps: 30 },
        16,
      ),
      background: {
        color: "#1a120d",
        image: "assets/caishen-readable.png",
        position: { x: 74, y: 50 },
        brightness: 0.78,
        blur: 0,
        overlay: "#120c08",
        overlayOpacity: 0.48,
      },
    },
  },
  scene: {
    layers: [
      {
        id: "caishen-readable-background",
        type: "image",
        asset: "assets/caishen-readable.png",
        opacity: 1,
        blendMode: "normal",
        parallax: 7,
      },
      {
        id: "caishen-readable-vignette",
        type: "vignette",
        opacity: 0.2,
        blendMode: "multiply",
        parallax: 0,
      },
    ],
    entities: [],
  },
  assets: [
    {
      id: "caishen-readable-background",
      path: "assets/caishen-readable.png",
      type: "background",
      license: "CC-BY-4.0",
    },
    {
      id: "caishen-readable-preview",
      path: "previews/caishen-readable.png",
      type: "preview",
      license: "CC-BY-4.0",
    },
  ],
  locales: {
    en: {
      name: "Caishen Readable",
      description:
        "A warm Caishen desk scene with light surfaces kept readable for work.",
    },
    "zh-CN": {
      name: "财神清爽可读",
      description: "暖色财神桌面场景，保留浅色高可读工作区表面。",
    },
  },
};

export const builtinThemes = [
  nativeRefined,
  gildedGrandeur,
  caishenReadable,
  merryBigTop,
  nocturneStudio,
  quietGarden,
];
